
services:
  postgres:
    image: postgres:15
    container_name: task-system-postgres
    environment:
      POSTGRES_DB: task_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweapril
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-system-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: task-system-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - task-system-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: TaskSystem/Dockerfile
    container_name: task-system-api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "6000:80"
    volumes:
      - ./logs:/app/logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__UserDbContext=User ID=postgres;Password=qweapril;Host=postgres;Port=5432;Database=task_system_db;
      - ConnectionStrings__JobProjectDbContext=User ID=postgres;Password=qweapril;Host=postgres;Port=5432;Database=task_system_db;
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
    networks:
      - task-system-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: task-system-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - task-system-network

volumes:
  postgres_data:
  rabbitmq_data:
  logs:

networks:
  task-system-network:
    driver: bridge